{{- if .Values.secrets.onepassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "openclaw.secretName" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.secrets.onepassword.itemPath | quote }}
{{- end }}
