apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openclaw.fullname" . }}-config
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.nfs.enabled }}
  storageClassName: ""
  volumeName: {{ include "openclaw.fullname" . }}-nfs
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
